name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: none
version: 2.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  # the annotation package containing @freezed
  freezed_annotation: ^2.4.1
  go_router: ^14.0.2
  intl: ^0.18.1
  # the annotation package for json_serializable
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3

dev_dependencies:
  # a tool for running code generators
  build_runner: ^2.4.9
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  import_sorter: ^4.6.0
  mocktail: ^1.0.3
  random_string: ^2.3.1
  # the code generator
  riverpod_generator: ^2.4.0
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.10

dependency_overrides:
  firebase_auth_web:
    git:
      url: https://github.com/firebase/flutterfire
      ref: master
      path: packages/firebase_auth/firebase_auth_web
  web: ^0.4.2

# https://github.com/frencojobs/derry
# `dart pub global activate derry`
scripts: derry.yaml

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
